In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/Delhi_raw.csv')

In [3]:
import warnings


warnings.filterwarnings("ignore")  # avoid printing out absolute paths

In [4]:
df.isna().sum()

from_date        0
to_date          0
pm25             0
pm10            50
no               0
nh3              0
no2             24
nox              0
so2             24
co               0
ozone            9
bp               0
wind_speed       0
air_temp        89
humidity         0
rainfall      3186
dtype: int64

In [5]:
df_new = df.sort_values(['from_date', 'to_date'])

# Set time index
df_new = df_new.set_index(['from_date', 'to_date'])

interpolated_df = df_new.interpolate(
    method='linear'
)

# Reset index if needed
interpolated_df = interpolated_df.reset_index()

interpolated_df.head()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall
0,2017-01-01 00:00:00,2017-01-01 01:00:00,212.535000,326.436250,54.380909,82.325000,51.679091,99.992000,16.894,2.032500,20.7800,791.506,0.565000,12.128,85.467143,0.0
1,2017-01-01 01:00:00,2017-01-01 02:00:00,221.626667,349.794286,57.869000,81.743333,50.840000,104.844444,15.530,2.308571,20.2050,791.420,0.595000,11.600,86.110000,0.0
2,2017-01-01 02:00:00,2017-01-01 03:00:00,217.650000,336.096250,42.166364,71.381667,43.699091,78.736000,13.922,1.623750,46.0625,791.380,0.498333,11.336,86.748571,0.0
3,2017-01-01 03:00:00,2017-01-01 04:00:00,226.055000,307.732500,41.658182,70.268333,38.291818,72.843000,13.780,1.568571,27.9700,791.540,0.531667,10.564,86.732857,0.0
4,2017-01-01 04:00:00,2017-01-01 05:00:00,219.325556,277.064286,56.181000,61.455000,34.336000,92.034444,15.322,1.868333,16.5950,791.634,0.386667,9.900,87.377143,0.0

In [6]:
interpolated_df["from_date"] = pd.to_datetime(interpolated_df['from_date'])
interpolated_df['Date'] = interpolated_df["from_date"].dt.date
interpolated_df.head()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date
0,2017-01-01 00:00:00,2017-01-01 01:00:00,212.535000,326.436250,54.380909,82.325000,51.679091,99.992000,16.894,2.032500,20.7800,791.506,0.565000,12.128,85.467143,0.0,2017-01-01
1,2017-01-01 01:00:00,2017-01-01 02:00:00,221.626667,349.794286,57.869000,81.743333,50.840000,104.844444,15.530,2.308571,20.2050,791.420,0.595000,11.600,86.110000,0.0,2017-01-01
2,2017-01-01 02:00:00,2017-01-01 03:00:00,217.650000,336.096250,42.166364,71.381667,43.699091,78.736000,13.922,1.623750,46.0625,791.380,0.498333,11.336,86.748571,0.0,2017-01-01
3,2017-01-01 03:00:00,2017-01-01 04:00:00,226.055000,307.732500,41.658182,70.268333,38.291818,72.843000,13.780,1.568571,27.9700,791.540,0.531667,10.564,86.732857,0.0,2017-01-01
4,2017-01-01 04:00:00,2017-01-01 05:00:00,219.325556,277.064286,56.181000,61.455000,34.336000,92.034444,15.322,1.868333,16.5950,791.634,0.386667,9.900,87.377143,0.0,2017-01-01

In [7]:
interpolated_df.isna().sum()

from_date     0
to_date       0
pm25          0
pm10          0
no            0
nh3           0
no2           0
nox           0
so2           0
co            0
ozone         0
bp            0
wind_speed    0
air_temp      0
humidity      0
rainfall      0
Date          0
dtype: int64

In [8]:
interpolated_df.shape

(54744, 17)

In [9]:
df_new = interpolated_df

In [10]:
df_new['time_idx'] = range(1, len(df_new) + 1)

In [11]:
print(len(df_new['time_idx'].unique()))

54744

In [12]:
df_new.head()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx
0,2017-01-01 00:00:00,2017-01-01 01:00:00,212.535000,326.436250,54.380909,82.325000,51.679091,99.992000,16.894,2.032500,20.7800,791.506,0.565000,12.128,85.467143,0.0,2017-01-01,1
1,2017-01-01 01:00:00,2017-01-01 02:00:00,221.626667,349.794286,57.869000,81.743333,50.840000,104.844444,15.530,2.308571,20.2050,791.420,0.595000,11.600,86.110000,0.0,2017-01-01,2
2,2017-01-01 02:00:00,2017-01-01 03:00:00,217.650000,336.096250,42.166364,71.381667,43.699091,78.736000,13.922,1.623750,46.0625,791.380,0.498333,11.336,86.748571,0.0,2017-01-01,3
3,2017-01-01 03:00:00,2017-01-01 04:00:00,226.055000,307.732500,41.658182,70.268333,38.291818,72.843000,13.780,1.568571,27.9700,791.540,0.531667,10.564,86.732857,0.0,2017-01-01,4
4,2017-01-01 04:00:00,2017-01-01 05:00:00,219.325556,277.064286,56.181000,61.455000,34.336000,92.034444,15.322,1.868333,16.5950,791.634,0.386667,9.900,87.377143,0.0,2017-01-01,5

In [13]:
df_new.columns

Index(['from_date', 'to_date', 'pm25', 'pm10', 'no', 'nh3', 'no2', 'nox',
       'so2', 'co', 'ozone', 'bp', 'wind_speed', 'air_temp', 'humidity',
       'rainfall', 'Date', 'time_idx'],
      dtype='object')

In [14]:
df_new['city'] = "Delhi"
df_new.head()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx,city
0,2017-01-01 00:00:00,2017-01-01 01:00:00,212.535000,326.436250,54.380909,82.325000,51.679091,99.992000,16.894,2.032500,20.7800,791.506,0.565000,12.128,85.467143,0.0,2017-01-01,1,Delhi
1,2017-01-01 01:00:00,2017-01-01 02:00:00,221.626667,349.794286,57.869000,81.743333,50.840000,104.844444,15.530,2.308571,20.2050,791.420,0.595000,11.600,86.110000,0.0,2017-01-01,2,Delhi
2,2017-01-01 02:00:00,2017-01-01 03:00:00,217.650000,336.096250,42.166364,71.381667,43.699091,78.736000,13.922,1.623750,46.0625,791.380,0.498333,11.336,86.748571,0.0,2017-01-01,3,Delhi
3,2017-01-01 03:00:00,2017-01-01 04:00:00,226.055000,307.732500,41.658182,70.268333,38.291818,72.843000,13.780,1.568571,27.9700,791.540,0.531667,10.564,86.732857,0.0,2017-01-01,4,Delhi
4,2017-01-01 04:00:00,2017-01-01 05:00:00,219.325556,277.064286,56.181000,61.455000,34.336000,92.034444,15.322,1.868333,16.5950,791.634,0.386667,9.900,87.377143,0.0,2017-01-01,5,Delhi

In [15]:
df_new = df_new.sort_values("Date")

In [16]:
df_new.to_csv("Delhi_finaldataset_2017.csv")

In [17]:
df_new["Date"] = pd.to_datetime(df_new["Date"])
train_data = df_new[df_new["Date"] < "2023-01-01"].copy()
test_data  = df_new[df_new["Date"] >= "2023-01-01"].copy()

In [18]:
test_data.head()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx,city
52597,2023-01-01 13:00:00,2023-01-01 14:00:00,94.043333,151.719143,12.323714,54.371667,23.361892,26.170882,8.574333,0.790000,54.318378,981.173913,0.942692,19.919091,51.103571,0.0,2023-01-01,52598,Delhi
52598,2023-01-01 14:00:00,2023-01-01 15:00:00,85.661111,144.775429,16.484857,54.456333,23.872973,30.449706,8.226667,0.851875,58.064324,980.622174,1.052308,19.742727,50.167143,0.0,2023-01-01,52599,Delhi
52599,2023-01-01 15:00:00,2023-01-01 16:00:00,82.441111,141.947714,15.008286,55.107000,24.905946,29.185882,8.385000,0.789687,57.227838,980.620435,1.174615,19.340909,50.949286,0.0,2023-01-01,52600,Delhi
52600,2023-01-01 16:00:00,2023-01-01 17:00:00,81.223889,153.056286,19.547222,53.856000,26.318108,28.998529,8.189333,0.842187,50.220541,980.596522,0.904615,18.509545,53.502143,0.0,2023-01-01,52601,Delhi
52601,2023-01-01 17:00:00,2023-01-01 18:00:00,89.398889,159.123143,20.731143,54.028667,38.654865,41.929412,7.363000,1.071250,28.241351,980.608696,0.508846,16.952273,59.774286,0.0,2023-01-01,52602,Delhi

In [19]:
train_data.tail()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx,city
52563,2022-12-31 03:00:00,2022-12-31 04:00:00,226.254167,338.179167,13.674706,72.315714,26.615000,28.754687,5.592143,1.318333,10.775833,980.616522,1.193077,13.905455,86.690714,0.0,2022-12-31,52564,Delhi
52562,2022-12-31 02:00:00,2022-12-31 03:00:00,257.243056,375.635833,17.581765,74.864231,28.955429,34.980625,5.749259,1.454167,8.446389,980.727391,1.148462,13.882727,86.935357,0.0,2022-12-31,52563,Delhi
52561,2022-12-31 01:00:00,2022-12-31 02:00:00,312.226944,455.862500,33.032000,81.546897,34.650811,52.609091,6.531333,1.619310,8.711250,980.810000,0.987308,13.819091,86.265357,0.0,2022-12-31,52562,Delhi
52560,2022-12-31 00:00:00,2022-12-31 01:00:00,355.172500,529.696944,70.482286,81.367931,44.688649,92.658788,7.195000,2.085938,8.575833,980.927826,0.750769,13.661364,85.190000,0.0,2022-12-31,52561,Delhi
52570,2022-12-31 10:00:00,2022-12-31 11:00:00,119.037297,170.385429,24.822286,67.856429,23.960833,39.667273,6.544483,0.906061,17.733056,982.455652,1.693462,15.810909,73.050357,0.0,2022-12-31,52571,Delhi

In [20]:
train_data.to_csv('Delhi_train_data_2017_no2.csv')
test_data.to_csv('Delhi_test_data_2017_no2.csv')

In [ ]:
test_data  = df_new[df_new["Date"] >= "2023-01-01"].copy()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx,city
52563,2022-12-31 03:00:00,2022-12-31 04:00:00,226.254167,338.179167,13.674706,72.315714,26.615000,28.754687,5.592143,1.318333,10.775833,980.616522,1.193077,13.905455,86.690714,0.0,2022-12-31,52564,Delhi
52562,2022-12-31 02:00:00,2022-12-31 03:00:00,257.243056,375.635833,17.581765,74.864231,28.955429,34.980625,5.749259,1.454167,8.446389,980.727391,1.148462,13.882727,86.935357,0.0,2022-12-31,52563,Delhi
52561,2022-12-31 01:00:00,2022-12-31 02:00:00,312.226944,455.862500,33.032000,81.546897,34.650811,52.609091,6.531333,1.619310,8.711250,980.810000,0.987308,13.819091,86.265357,0.0,2022-12-31,52562,Delhi
52560,2022-12-31 00:00:00,2022-12-31 01:00:00,355.172500,529.696944,70.482286,81.367931,44.688649,92.658788,7.195000,2.085938,8.575833,980.927826,0.750769,13.661364,85.190000,0.0,2022-12-31,52561,Delhi
52570,2022-12-31 10:00:00,2022-12-31 11:00:00,119.037297,170.385429,24.822286,67.856429,23.960833,39.667273,6.544483,0.906061,17.733056,982.455652,1.693462,15.810909,73.050357,0.0,2022-12-31,52571,Delhi

In [24]:
test_data.tail()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx,city
54721,2023-03-31 01:00:00,2023-03-31 02:00:00,23.952500,37.875714,15.849714,51.942143,26.730571,36.952727,6.908929,0.924848,18.199063,964.820000,0.965600,17.665000,79.839630,0.173333,2023-03-31,54722,Delhi
54720,2023-03-31 00:00:00,2023-03-31 01:00:00,22.070937,35.489714,19.685556,48.000690,31.598333,43.068529,6.682857,0.990606,12.834857,965.301818,0.757600,17.976818,77.738889,0.043333,2023-03-31,54721,Delhi
54742,2023-03-31 22:00:00,2023-03-31 23:00:00,33.920556,83.395135,14.889459,44.985333,28.277027,35.326286,9.561724,1.011176,23.071389,966.978696,1.028846,18.055000,73.200000,0.000000,2023-03-31,54743,Delhi
54730,2023-03-31 10:00:00,2023-03-31 11:00:00,31.510294,55.650278,17.964722,47.371724,21.534167,33.280882,8.728276,0.997353,31.171111,965.987619,1.356923,20.202273,66.963571,0.000000,2023-03-31,54731,Delhi
54743,2023-03-31 23:00:00,2023-04-01 00:00:00,27.461389,68.767838,15.776757,43.880667,28.740000,37.152857,8.739655,0.986765,19.760556,965.149130,0.677308,17.667727,76.022857,0.000000,2023-03-31,54744,Delhi

(2160, 19)

In [32]:
val = test_data[test_data["Date"] < "2023-03-01"].copy()
test  = test_data[test_data["Date"] >= "2023-03-01"].copy()

In [33]:
val.head()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx,city
52597,2023-01-01 13:00:00,2023-01-01 14:00:00,94.043333,151.719143,12.323714,54.371667,23.361892,26.170882,8.574333,0.790000,54.318378,981.173913,0.942692,19.919091,51.103571,0.0,2023-01-01,52598,Delhi
52598,2023-01-01 14:00:00,2023-01-01 15:00:00,85.661111,144.775429,16.484857,54.456333,23.872973,30.449706,8.226667,0.851875,58.064324,980.622174,1.052308,19.742727,50.167143,0.0,2023-01-01,52599,Delhi
52599,2023-01-01 15:00:00,2023-01-01 16:00:00,82.441111,141.947714,15.008286,55.107000,24.905946,29.185882,8.385000,0.789687,57.227838,980.620435,1.174615,19.340909,50.949286,0.0,2023-01-01,52600,Delhi
52600,2023-01-01 16:00:00,2023-01-01 17:00:00,81.223889,153.056286,19.547222,53.856000,26.318108,28.998529,8.189333,0.842187,50.220541,980.596522,0.904615,18.509545,53.502143,0.0,2023-01-01,52601,Delhi
52601,2023-01-01 17:00:00,2023-01-01 18:00:00,89.398889,159.123143,20.731143,54.028667,38.654865,41.929412,7.363000,1.071250,28.241351,980.608696,0.508846,16.952273,59.774286,0.0,2023-01-01,52602,Delhi

In [34]:
val.tail()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx,city
53982,2023-02-28 06:00:00,2023-02-28 07:00:00,119.119730,227.606486,106.468056,53.455926,37.400000,124.844118,7.965667,1.439688,6.448919,970.941739,0.426923,16.264545,81.598571,0.0,2023-02-28,53983,Delhi
53983,2023-02-28 07:00:00,2023-02-28 08:00:00,126.779189,246.211081,119.089722,53.933704,41.772222,137.475294,8.419000,1.625000,6.738571,971.514783,0.550769,16.843182,80.647857,0.0,2023-02-28,53984,Delhi
53984,2023-02-28 08:00:00,2023-02-28 09:00:00,140.924324,292.597027,96.738919,58.177500,55.888611,129.206176,10.753333,1.611212,7.856389,972.070435,0.701923,19.789091,68.645000,0.0,2023-02-28,53985,Delhi
53985,2023-02-28 09:00:00,2023-02-28 10:00:00,143.231892,315.876486,59.601892,57.312857,55.851892,95.036471,14.572000,1.372121,13.608611,972.468696,0.728462,22.652273,53.602857,0.0,2023-02-28,53986,Delhi
53981,2023-02-28 05:00:00,2023-02-28 06:00:00,106.730000,217.220541,96.978649,53.771481,38.276667,119.865294,8.689333,1.345625,5.987568,970.485217,0.579231,16.421818,80.871786,0.0,2023-02-28,53982,Delhi

In [35]:
test.head()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx,city
54014,2023-03-01 14:00:00,2023-03-01 15:00:00,68.795405,180.370270,14.642000,50.506897,27.015833,32.928529,12.682857,0.798529,60.389722,971.196818,0.896000,26.612381,38.055556,0.0,2023-03-01,54015,Delhi
54015,2023-03-01 15:00:00,2023-03-01 16:00:00,60.332973,156.822162,15.875556,48.303793,26.840811,33.813143,12.094643,0.813529,65.791111,969.975714,0.951667,26.844000,36.867308,0.0,2023-03-01,54016,Delhi
54016,2023-03-01 16:00:00,2023-03-01 17:00:00,54.663243,144.447568,14.721944,50.233000,27.311892,32.552000,10.217143,0.838824,62.387778,970.650455,0.916000,26.158571,37.981852,0.0,2023-03-01,54017,Delhi
54017,2023-03-01 17:00:00,2023-03-01 18:00:00,49.912432,144.702703,19.187222,49.346333,36.887105,40.959429,9.211429,0.975294,42.729722,970.606364,0.935600,24.775238,41.598148,0.0,2023-03-01,54018,Delhi
54018,2023-03-01 18:00:00,2023-03-01 19:00:00,54.025278,179.613056,36.072162,48.283667,54.673947,68.156857,9.657586,1.392424,17.230000,970.869545,0.634400,22.013810,50.239259,0.0,2023-03-01,54019,Delhi

In [36]:
test.tail()

,from_date,to_date,pm25,pm10,no,nh3,no2,nox,so2,co,ozone,bp,wind_speed,air_temp,humidity,rainfall,Date,time_idx,city
54721,2023-03-31 01:00:00,2023-03-31 02:00:00,23.952500,37.875714,15.849714,51.942143,26.730571,36.952727,6.908929,0.924848,18.199063,964.820000,0.965600,17.665000,79.839630,0.173333,2023-03-31,54722,Delhi
54720,2023-03-31 00:00:00,2023-03-31 01:00:00,22.070937,35.489714,19.685556,48.000690,31.598333,43.068529,6.682857,0.990606,12.834857,965.301818,0.757600,17.976818,77.738889,0.043333,2023-03-31,54721,Delhi
54742,2023-03-31 22:00:00,2023-03-31 23:00:00,33.920556,83.395135,14.889459,44.985333,28.277027,35.326286,9.561724,1.011176,23.071389,966.978696,1.028846,18.055000,73.200000,0.000000,2023-03-31,54743,Delhi
54730,2023-03-31 10:00:00,2023-03-31 11:00:00,31.510294,55.650278,17.964722,47.371724,21.534167,33.280882,8.728276,0.997353,31.171111,965.987619,1.356923,20.202273,66.963571,0.000000,2023-03-31,54731,Delhi
54743,2023-03-31 23:00:00,2023-04-01 00:00:00,27.461389,68.767838,15.776757,43.880667,28.740000,37.152857,8.739655,0.986765,19.760556,965.149130,0.677308,17.667727,76.022857,0.000000,2023-03-31,54744,Delhi

In [37]:
test.shape

(744, 19)

In [39]:
test.to_csv('test.csv')
val.to_csv('val.csv')